# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113bUVFk4aAzIUYlGcGHuqLAW52BKlo1o
"""

!pip install ultralytics

!pip install onnx

import torch
from ultralytics import YOLO
import pathlib

# Paths & sizes (adjust if needed)
PT_MODEL   = "/content/yolo12n.pt"
INPUT_SIZE = (192, 192)  # (H, W)
BASE       = pathlib.Path("/content/yolo2tflite_workflow")
BASE.mkdir(exist_ok=True, parents=True)
ONNX_PATH  = BASE/"yolo12n.onnx"

# 1) Load YOLOv12 and set to eval/CPU
yolov12 = YOLO(PT_MODEL).model.eval().to("cpu")

# 2) Dummy input matching your target shape
dummy = torch.randn(1, 3, *INPUT_SIZE)

# 3) Export to ONNX (static axes)
torch.onnx.export(
    yolov12,                  # the PyTorch model
    dummy,                    # dummy input
    str(ONNX_PATH),           # where to save .onnx
    opset_version=13,         # ensure compatibility
    input_names=["images"],   # name of the input node
    output_names=["outputs"], # name of the output node
    dynamic_axes={}           # **no** dynamic axes = fully static
)

print("✔ ONNX model exported to:", ONNX_PATH)



import onnx, numpy as np
from onnx import helper, numpy_helper, shape_inference

# ─── Patch the single Add node that has 32 vs 16 channels ────────────────────
model = onnx.load(str(ONNX_PATH))
graph = model.graph

# Locate the specific Add by its exact name
target = "wa/model.2/m.0/Add"
for node in graph.node:
    if node.name == target and node.op_type == "Add":
        a, b = node.input  # a has C=32, b has C=16

        # Pull out the channel dims from the inferred shape info
        c0 = c1 = None
        for vi in graph.value_info:
            if vi.name == a:
                c0 = vi.type.tensor_type.shape.dim[1].dim_value
            if vi.name == b:
                c1 = vi.type.tensor_type.shape.dim[1].dim_value
        assert c0 is not None and c1 is not None, "Shape info missing"

        diff = int(c0 - c1)  # should be 16
        # Create a pads initializer: [N_beg,C_beg,H_beg,W_beg, N_end,C_end,H_end,W_end]
        pads = np.array([0,0,0,0, 0,diff,0,0], dtype=np.int64)
        pads_name = f"{b}_pads"
        graph.initializer.append(
            numpy_helper.from_array(pads, name=pads_name)
        )

        # Insert a Pad node on the smaller-C branch
        padded = f"{b}_padded"
        pad_node = helper.make_node(
            "Pad",
            inputs=[b, pads_name],
            outputs=[padded],
            name=f"{b}_pad",
            mode="constant"
        )
        idx = list(graph.node).index(node)
        graph.node.insert(idx, pad_node)

        # Reroute the Add to use the padded tensor
        node.input[1] = padded
        break

# Write back with fresh shape inference
model = shape_inference.infer_shapes(model)
onnx.save(model, str(ONNX_PATH))
print("✔ ONNX Add node patched (32 vs 16) and shape-fixed")

!pip install onnx2pytorch

import onnx
from onnx import shape_inference

# 1) Load & infer shapes
onnx_model = onnx.load("/content/yolo2tflite_workflow/yolo12n.onnx")
onnx_model = shape_inference.infer_shapes(onnx_model)

# 2) Grab the first input's dims, replacing any 0 or unknown dims with 1
input_info = onnx_model.graph.input[0].type.tensor_type.shape
dims = [
    (d.dim_value if (d.dim_value and d.dim_value > 0) else 1)
    for d in input_info.dim
]
print("Detected input shape:", dims)

#!/usr/bin/env python3
"""
Convert an ONNX model to a PyTorch .pt model using onnx2pytorch.

Usage:
    python onnx_to_pt.py --onnx_model path/to/model.onnx --output_model path/to/model.pt
"""

# 3) Conversion function
import torch
import onnx
from onnx2pytorch import ConvertModel

def onnx_to_pytorch(onnx_path: str, output_path: str, dummy_input_shape=(1,3,224,224)):
    # Load & verify ONNX
    model_onnx = onnx.load(onnx_path)
    onnx.checker.check_model(model_onnx)
    print(f"✅ ONNX loaded: {onnx_path}")

    # Convert
    model_pt = ConvertModel(model_onnx)
    model_pt.eval()
    print("✅ Converted to PyTorch nn.Module")

    # Dummy forward-pass (shape check)
    dummy = torch.randn(dummy_input_shape)
    with torch.no_grad():
        _ = model_pt(dummy)
    print(f"✅ Forward OK with dummy input {dummy_input_shape}")

    # Save state_dict
    torch.save(model_pt.state_dict(), output_path)
    print(f"✅ Saved PyTorch state_dict to {output_path}")

# 4) Point to your files and run
onnx_file = "/content/yolo2tflite_workflow/yolo12n.onnx"   # or "/content/model.onnx"
pt_file   = "/content/yolo2tflite_workflow/yolo12n.pt"     # or "/content/model.pt"
input_shape = (1, 3, 192, 192)                    # adjust if needed

onnx_to_pytorch(onnx_file, pt_file, dummy_input_shape=input_shape)

!pip install onnxruntime

import torch
from ultralytics import YOLO

# 1. Load your YOLO model and switch to eval
yolo = YOLO('/content/yolo12n.pt')
model = yolo.model.eval()          # <-- grab the raw nn.Module

# 2. Script the pure nn.Module (captures all shape logic)
scripted = torch.jit.script(model)

# 3. Freeze it (constant-folds branches & shape ops)
frozen = torch.jit.freeze(scripted)

# 4. Save out your static-shape TorchScript
torch.jit.save(frozen, 'yolo12n_static.pt')

from ultralytics import YOLO

# Load the YOLO11 model
model = YOLO("/content/yolo11n-obb.pt")

# Export the model to TFLite format
model.export(format="tflite")  # creates 'yolo11n_float32.tflite'

from ultralytics import YOLO

import torch
# 1. Create the YOLO wrapper (not the raw .model)
yolo = YOLO('/content/yolo11n.pt')  # your detect weights



# Trace it on a dummy 1×3×192×192 input
example = torch.randn(1, 3, 256, 256)
traced = torch.jit.trace(model, example)

# Save under your desired .pt name
torch.jit.save(traced, 'yolov8_detect_192.pt')
print("Saved yolov8_detect_192.pt")



from ultralytics import YOLO
import torch

# 1. Load your detection model
yolo = YOLO('/content/yolo11n.pt')  # or 'yolov8n.pt'

# 2. Export to a single TorchScript .pt for object detection @ 192×192
out = model.export(
    format='torchscript',
    task='detect',
    imgsz=(192, 192),
    dynamic=False     # static shape
)

# .model is the raw nn.Module inside the Ultralytics wrapper:
model: torch.nn.Module = yolo.model
model.eval()

# 2. Create a dummy input matching 1×3×192×192
example_input = torch.randn(1, 3, 192, 192)

# 3. Trace the model
traced = torch.jit.trace(model, example_input)

# 4. Save out a plain .pt
torch.jit.save(traced, 'yolov8_detect_192.pt')
print("Saved yolov8_detect_192.pt")

print("Generated files:", out.files)

# Cell 3 — user‐configurable variables
import os, tensorflow as tf

# Path to your SavedModel directory (or .h5/.keras) in Colab:
SAVED_MODEL_PATH    = "/content/yolo11n-obb_saved_model"

# Where to write the quantized TFLite file:
OUTPUT_TFLITE_PATH  = "/content/model_int8.tflite"

# Directory where your COCO train2017 images live:
COCO_IMAGE_DIR      = "/content/drive/MyDrive/train2017"

# Model input size (H, W):
IMAGE_SIZE          = (224, 224)

# Number of calibration samples to use:
NUM_CALIB_SAMPLES   = 100

# I/O dtype (uint8 or tf.int8):
IO_DTYPE            = tf.uint8

import tensorflow as tf

# Replace with your actual float32 .tflite
FLOAT_TFLITE = "/content/yolo11n-obb_saved_model/yolo11n-obb_float32.tflite"

interpreter = tf.lite.Interpreter(model_path=FLOAT_TFLITE)
interpreter.allocate_tensors()
inp = interpreter.get_input_details()[0]
print("Input tensor name:", inp["name"])
print("Expected shape:", inp["shape"])

# 1. Load your detection model
yolo = YOLO('/content/yolov8_detect_192.pt')  # or 'yolov8n.pt'

# 2. Export to a single TorchScript .pt for object detection @ 192×192
out = model.export(
    format='tf'
)

!pip install ultralytics

# Cell 1 — install dependencies
!pip install -q tensorflow pycocotools pillow numpy

# Cell 2 — (optional) mount Google Drive if your COCO images or SavedModel are there
from google.colab import drive
drive.mount('/content/drive')

# Cell 3 — full INT8 quantization script
import os
import glob
import numpy as np
import tensorflow as tf
from PIL import Image

# === User-configurable variables ===
# Path to your SavedModel directory:
SAVED_MODEL_PATH   = "/content/yolo11n-obb_saved_model"

# Output path for your fully-quantized TFLite:
OUTPUT_TFLITE_PATH = "/content/model_int8.tflite"

# Folder of COCO train2017 images (mounted Drive):
COCO_IMAGE_DIR     = "/content/drive/MyDrive/train2017"

# Must match your model’s [1, H, W, 3] → here H=W=1024
IMAGE_SIZE         = (1024, 1024)

# Number of calibration samples to run:
NUM_CALIB_SAMPLES  = 100

# I/O dtype: tf.uint8 (zero-point at 0) or tf.int8 (symmetric)
IO_DTYPE           = tf.uint8
# === End of user-configurable section ===

def representative_data_gen():
    """Yields NUM_CALIB_SAMPLES batches of shape (1,H,W,3) for calibration."""
    img_paths = glob.glob(os.path.join(COCO_IMAGE_DIR, "*.jpg")) \
              + glob.glob(os.path.join(COCO_IMAGE_DIR, "*.png"))
    for p in img_paths[:NUM_CALIB_SAMPLES]:
        img = Image.open(p).convert("RGB").resize(IMAGE_SIZE, Image.BILINEAR)
        arr = np.asarray(img, dtype=np.float32) / 255.0            # normalize to [0,1]
        tensor = tf.convert_to_tensor(arr, dtype=tf.float32)
        yield [tf.expand_dims(tensor, axis=0)]                    # shape (1,H,W,3)

# 1. Create the TFLiteConverter
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_PATH)

# 2. Enable full INT8 quantization (weights + activations)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen

# 3. Force all ops + I/O to INT8/uint8
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS_INT8,      # int8-only kernels
  tf.lite.OpsSet.SELECT_TF_OPS             # float fallback for everything else
]

converter.inference_input_type  = IO_DTYPE
converter.inference_output_type = IO_DTYPE

# 4. Convert and save
print("Converting to INT8… this may take a few minutes.")
tflite_model = converter.convert()
with open(OUTPUT_TFLITE_PATH, "wb") as f:
    f.write(tflite_model)
print("✅ Fully-quantized TFLite model saved to", OUTPUT_TFLITE_PATH)

# Cell 4 — build the representative dataset directly from your COCO image folder
import glob

def representative_data_gen():
    # grab all .jpg/.png files in your COCO folder
    img_paths = glob.glob(os.path.join(COCO_IMAGE_DIR, "*.jpg")) \
              + glob.glob(os.path.join(COCO_IMAGE_DIR, "*.png"))
    # shuffle if you like:
    img_paths = img_paths[:NUM_CALIB_SAMPLES]
    for img_path in img_paths:
        # read, decode, resize, normalize
        img = tf.io.read_file(img_path)
        img = tf.image.decode_jpeg(img, channels=3)  # or decode_png
        img = tf.image.resize(img, IMAGE_SIZE)
        img = tf.cast(img, tf.float32) / 255.0
        # add batch dim
        yield [tf.expand_dims(img, 0)]

# Cell 5 — quantize and save
# 1) Create converter
if os.path.isdir(SAVED_MODEL_PATH):
    converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_PATH)
elif SAVED_MODEL_PATH.lower().endswith((".h5", ".keras")):
    model = tf.keras.models.load_model(SAVED_MODEL_PATH)
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
else:
    raise ValueError(f"Invalid model path: {SAVED_MODEL_PATH}")

# 2) Enable full INT8 quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen

# 3) Force all ops + I/O to INT8/uint8
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type  = IO_DTYPE
converter.inference_output_type = IO_DTYPE

# 4) Convert & write out
print("Converting… this may take a few minutes.")
tflite_model = converter.convert()
with open(OUTPUT_TFLITE_PATH, "wb") as f:
    f.write(tflite_model)
print(f"✅ Fully-quantized TFLite model saved to {OUTPUT_TFLITE_PATH}")



# 3) Monkey-patch torch.nn.functional.interpolate to handle list-of-tensors scale_factor
import torch
import torch.nn.functional as F
_orig_interpolate = F.interpolate

def _patched_interpolate(input, size=None, scale_factor=None, mode='nearest',
                         align_corners=None, recompute_scale_factor=None, antialias=None):
    # If size is None and scale_factor is list/tuple of Tensors, compute output size
    if size is None and isinstance(scale_factor, (list, tuple)) and \
       all(isinstance(f, torch.Tensor) for f in scale_factor):
        # Convert each tensor factor to float
        factors = [float(f.item()) for f in scale_factor]
        _, _, H, W = input.shape
        new_h = int(H * factors[0])
        new_w = int(W * factors[1])
        size = (new_h, new_w)
        scale_factor = None
    return _orig_interpolate(input, size=size, scale_factor=scale_factor,
                              mode=mode, align_corners=align_corners,
                              recompute_scale_factor=recompute_scale_factor,
                              antialias=antialias)
# Override the original function
F.interpolate = _patched_interpolate

# 4) Conversion function with shape inference, output-fix, and dummy forward
import onnx
from onnx import shape_inference, helper, TensorProto
import onnxruntime as ort
from onnx2pytorch import ConvertModel

def onnx_to_pytorch_with_patch(onnx_path: str, output_path: str):
    # --- Load the ONNX model ---
    model_onnx = onnx.load(onnx_path)

    # --- Infer shapes ---
    model_onnx = shape_inference.infer_shapes(model_onnx)

    # --- Fix graph outputs: ensure only real outputs are listed ---
    # Use ONNX Runtime to discover actual output names
    sess = ort.InferenceSession(onnx_path, providers=['CPUExecutionProvider'])
    output_names = [o.name for o in sess.get_outputs()]
    # Clear existing outputs and set correct ones
    del model_onnx.graph.output[:]
    for name in output_names:
        # Create a generic FLOAT ValueInfoProto with unknown dims
        vi = helper.make_tensor_value_info(name, TensorProto.FLOAT, None)
        model_onnx.graph.output.append(vi)

    # --- Extract input dimensions (replace unknown with 1) ---
    input_info = model_onnx.graph.input[0].type.tensor_type.shape.dim
    dims = [(d.dim_value if (d.dim_value and d.dim_value > 0) else 1) for d in input_info]
    print(f"Detected input shape: {dims}")

    # --- Convert to PyTorch ---
    pt_model = ConvertModel(model_onnx)
    pt_model.eval()
    print("✅ Converted to PyTorch nn.Module")

    # --- Dummy forward with inferred shape ---
    dummy = torch.randn(*dims)
    with torch.no_grad():
        _ = pt_model(dummy)
    print(f"✅ Dummy forward pass OK with input shape {dims}")

    # --- Save state_dict ---
    torch.save(pt_model.state_dict(), output_path)
    print(f"✅ Saved PyTorch state_dict to {output_path}")


# 4) Point to your files and run
onnx_file = "/content/yolo2tflite_workflow/yolo12n.onnx"   # or "/content/model.onnx"
pt_file   = "/content/yolo2tflite_workflow/yolo12n.pt"     # or "/content/model.pt"
input_shape = (1, 3, 192, 192)                    # adjust if needed
onnx_to_pytorch_with_patch(onnx_file, pt_file)

from ultralytics import YOLO
import torch
import torch.nn as nn
# Load your original weights
yolo = YOLO('/content/yolo11n.pt')

raw_model: nn.Module = yolo.model.eval()

# 2. Define a wrapper with a single-arg forward
class TSWrapper(nn.Module):
    def __init__(self, model: nn.Module):
        super().__init__()
        self.model = model

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # call the raw model, ignore any extra args internally
        return self.model(x)

# 3. Instantiate & script the wrapper
wrapped = TSWrapper(raw_model)
scripted = torch.jit.script(wrapped)

# 4. Save to a flat .pt
torch.jit.save(scripted, 'yolov8_detect_anysize.pt')
print("Saved yolov8_detect_anysize.pt")

from ultralytics import YOLO
model = YOLO('yolo11n.pt')          # o 'yolov11n.pt'

model.export(
    format='onnx',
    imgsz=192,
    opset=12,        # opset testato da ST
    simplify=True,   # riduce il grafo
    dynamic=False,   # shape fisse richieste
    nms=False        # NMS & Softmax rimossi
)

!python -m onnxsim yolo11n.onnx yolo11n_simple.onnx

from ultralytics import YOLO
model = YOLO("yolo11n.pt")      # or yolov8m.pt

model.export(
    format   = "onnx",
    imgsz    = 192,             # STM32 examples are all 640×640
    opset    = 13,              # last opset fully supported by STM32 Edge-AI 2.2
    dynamic  = False,           # <--  IMPORTANT
    nms      = False,           # <--  IMPORTANT
    simplify = True
)
# → yolo11n.onnx

import onnx
from onnx import helper

model = onnx.load("yolo11n.onnx")
new_nodes = []
for n in model.graph.node:
    if n.op_type == "Softmax":
        # replace with Identity to keep graph connected
        new_nodes.append(helper.make_node("Identity",
                                          inputs=n.input,
                                          outputs=n.output,
                                          name=n.name + "_identity"))
    else:
        new_nodes.append(n)
model.graph.ClearField("node")
model.graph.node.extend(new_nodes)
onnx.save(model, "yolo11n_no_softmax.onnx")

!pip install --upgrade onnx-simplifier==0.4.34
!python -m onnxsim \
       yolo11n_no_softmax.onnx \
       yolo11n_sim.onnx \
       --input-shape "1,3,640,640" \
       --enable-reshape-shape-inference

!pip install --upgrade onnxruntime==1.19.0 onnxruntime-tools

"""
quantize_stm32.py – YOLO11 → INT8 ONNX per STM32 Edge AI
─────────────────────────────────────────────────────────
• Input : yolo11n_clean.onnx (FP32, senza NMS)
• Output: yolo11n_int8.onnx  (INT8 QOperator, opset 12)
"""

import cv2, numpy as np, onnx
from pathlib import Path
from tqdm import tqdm
from onnxruntime.quantization import (
        quantize_static, CalibrationDataReader,
        QuantType, QuantFormat, CalibrationMethod)
from subprocess import run, CalledProcessError

SRC_MODEL  = "/content/yolo11n_clean.onnx"
SIM_MODEL  = "yolo11n_sim.onnx"
INT8_MODEL = "yolo11n_int8.onnx"
CALIB_DIR  = "/content/drive/MyDrive/train2017"           # 50–100 immagini RGB qualsiasi
IMG_SIZE   = 192                      # input size del tuo YOLO

# ────────────────────────────────────────────────────────────────
# 1. Rimuove Softmax se ancora presente
print("▸ Stripping Softmax (se presente)…")
model = onnx.load(SRC_MODEL)
new_nodes = [
    onnx.helper.make_node("Identity", n.input, n.output, n.name + "_id")
    if n.op_type == "Softmax" else n
    for n in model.graph.node
]
model.graph.ClearField("node")
model.graph.node.extend(new_nodes)
onnx.save(model, SRC_MODEL)

# 2. onnx-simplifier per shape statiche 1×3×640×640
print("▸ Congelo le shape con onnxsim…")
try:
    run(["python", "-m", "onnxsim", SRC_MODEL, SIM_MODEL,
         "--input-shape", f"1,3,{IMG_SIZE},{IMG_SIZE}"], check=True)
except CalledProcessError:
    raise SystemExit("onnxsim non trovato: pip install onnx-simplifier")

# 3. Reader per la PTQ
class CalibReader(CalibrationDataReader):
    def __init__(self, folder, input_name):
        self.files = list(Path(folder).glob("*"))
        self.input = input_name
        self.i = 0
    def get_next(self):
        if self.i >= len(self.files):
            return None
        img = cv2.cvtColor(cv2.imread(str(self.files[self.i])), cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE)).astype(np.float32) / 255.
        img = np.transpose(img, (2,0,1))[None]
        self.i += 1
        return {self.input: img}

print("▸ Carico il modello semplificato…")
m = onnx.load(SIM_MODEL)
inp_name = m.graph.input[0].name

print("▸ Quantizzazione INT8 (Entropy)…")
# … CalibReader e variabili   (uguali a prima) …

quantize_static(
    model_input             = SIM_MODEL,
    model_output            = INT8_MODEL,
    calibration_data_reader = CalibReader(CALIB_DIR, inp_name),

    # ①  Quantizza SOLO le convoluzioni, in formato QDQ ----------
    quant_format            = QuantFormat.QDQ,
    op_types_to_quantize    = ["Conv"],     # <-- NIENTE Sigmoid!
    # ------------------------------------------------------------

    activation_type         = QuantType.QInt8,
    weight_type             = QuantType.QInt8,
    calibrate_method        = CalibrationMethod.Entropy,
    per_channel             = True
)

print("✅  Fatto!  →", INT8_MODEL)
print("Ora puoi testarlo con: stedgeai analyze --model yolo11n_int8.onnx …")

from ultralytics import YOLO

model = YOLO('yolo11n.pt')          # nano weight ufficiale

model.export(
    format   = 'onnx',
    imgsz    = 192,                 # o 256/320 … come da tabella STM32
    opset    = 12,                  # ultimo totalmente supportato
    dynamic  = False,               # ← STM32 vieta shape dinamiche
    nms      = False,               # ← post-process fuori dal grafo
    simplify = True                 # primo pass di folding
)
# -->>  yolo11n.onnx

import onnx
from onnx import helper
m = onnx.load("yolo11n.onnx")
new = []
for n in m.graph.node:
    if n.op_type == "Softmax":
        new.append(helper.make_node("Identity", n.input, n.output,
                                    name=n.name+"_id"))
    else:
        new.append(n)
m.graph.ClearField("node"); m.graph.node.extend(new)
onnx.save(m, "yolo11n_no_sm.onnx")

!python -m onnxsim yolo11n_no_sm.onnx yolo11n_sim.onnx \
       --input-shape "1,3,192,192" \
       --enable-reshape-shape-inference

!pip install ultralytics

from ultralytics import YOLO

# Load a COCO-pretrained YOLOv5n model
model = YOLO("yolov5n.pt")

# Display model information (optional)
model.info()

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="coco8.yaml", epochs=20, imgsz=192,)

!pip install -U ultralytics

from ultralytics import YOLO

model = YOLO('/content/yolov8n.pt')          # nano weight ufficiale

model.export(format='tflite', imgsz=192, int8=True,
             data='coco128.yaml', nms=False)  # → yolo11n_int8.tflite

# Cell 1 — install dependencies
!pip install -q tensorflow pycocotools pillow numpy

# Cell 3 — full INT8 quantization script
import os
import glob
import numpy as np
import tensorflow as tf
from PIL import Image

# === User-configurable variables ===
# Path to your SavedModel directory:
SAVED_MODEL_PATH   = "/content/yolov5nu_wrapped"

# Output path for your fully-quantized TFLite:
OUTPUT_TFLITE_PATH = "/content/model_int8.tflite"

# Folder of COCO train2017 images (mounted Drive):
COCO_IMAGE_DIR     = "/content/drive/MyDrive/train2017"

# Must match your model’s [1, H, W, 3] → here H=W=1024
IMAGE_SIZE         = (192,192)

# Number of calibration samples to run:
NUM_CALIB_SAMPLES  = 300

# I/O dtype: tf.uint8 (zero-point at 0) or tf.int8 (symmetric)
IO_DTYPE           = tf.uint8
# === End of user-configurable section ===

def representative_data_gen():
    """Yields NUM_CALIB_SAMPLES batches of shape (1,H,W,3) for calibration."""
    img_paths = glob.glob(os.path.join(COCO_IMAGE_DIR, "*.jpg")) \
              + glob.glob(os.path.join(COCO_IMAGE_DIR, "*.png"))
    for p in img_paths[:NUM_CALIB_SAMPLES]:
        img = Image.open(p).convert("RGB").resize(IMAGE_SIZE, Image.BILINEAR)
        arr = np.asarray(img, dtype=np.float32) / 255.0            # normalize to [0,1]
        tensor = tf.convert_to_tensor(arr, dtype=tf.float32)
        yield [tf.expand_dims(tensor, axis=0)]                    # shape (1,H,W,3)

# 1. Create the TFLiteConverter
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_PATH)

# 2. Enable full INT8 quantization (weights + activations)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen

# 3. Force all ops + I/O to INT8/uint8
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS_INT8,      # int8-only kernels
  tf.lite.OpsSet.SELECT_TF_OPS             # float fallback for everything else
]

converter.inference_input_type  = IO_DTYPE
converter.inference_output_type = IO_DTYPE

# 4. Convert and save
print("Converting to INT8… this may take a few minutes.")
tflite_model = converter.convert()
with open(OUTPUT_TFLITE_PATH, "wb") as f:
    f.write(tflite_model)
print("✅ Fully-quantized TFLite model saved to", OUTPUT_TFLITE_PATH)

import tensorflow as tf

base = tf.saved_model.load("/content/yolov5nu_saved_model")
infer = base.signatures["serving_default"]

# structured_input_signature = (args, kwargs)
_, kwargs = infer.structured_input_signature

# build a list of TensorSpecs from the kwargs dict
input_specs = [
    tf.TensorSpec(spec.shape, spec.dtype, name=name)
    for name, spec in kwargs.items()
]

class WrapModel(tf.Module):
    def __init__(self, fn):
        super().__init__()
        self.fn = fn

    @tf.function(input_signature=input_specs)
    def __call__(self, *args, **kwargs):
        # unpack exactly like the original
        out = self.fn(*args, **kwargs)
        if isinstance(out, dict):
            key = next(iter(out))
            y = out[key]
        else:
            y = out
        return tf.transpose(y, perm=[0,2,1])

wrapped = WrapModel(infer)
tf.saved_model.save(wrapped, "/content/yolov5nu_wrapped")

import numpy as np
import tensorflow as tf

# load & allocate as before
interpreter = tf.lite.Interpreter(model_path="model_int8.tflite")
interpreter.allocate_tensors()

# get the input details
input_details = interpreter.get_input_details()
shape = input_details[0]['shape']          # e.g. [1, 192, 192, 3]
dtype = input_details[0]['dtype']          # e.g. np.uint8

# create a dummy input of the correct shape & type
inp = np.zeros(shape, dtype=dtype)

# now this will work
interpreter.set_tensor(input_details[0]['index'], inp)
interpreter.invoke()